### ISSUE TITLE
Having all inactive rules in rewrite.json throws NPE while hitting a resource.

### ISSUE THREAD

**Issue by subratpanda1** [flipkart-incubator/Poseidon#31]
The following rewrite.json will cause NPE

[
  {
    "active": false,
    "name": "ALL_URL_CONVERTER",
    "details": "Converts all URLs to /",
    "from": "^/.*$",
    "to": "/"
  }
]

**Comment by pmohankumar** [comment]
Fixed in poseidon 4.2.0
